### ISSUE TITLE
parent id and span id now have different formats post-propagation.

### ISSUE THREAD

**Issue by lizthegrey** [honeycombio/opentelemetry-exporter-go#27]
![Screenshot from 2019-10-10 10-07-35](https://user-images.githubusercontent.com/614704/66576483-cca2c180-eb45-11e9-835d-42c677c6d2df.png)

parent id now appears to be in decimal while span id is in hex, causing the traces to not line up.

**Comment by akvanhar** [comment]
Should be fixed by https://github.com/honeycombio/opentelemetry-exporter-go/pull/28
