### ISSUE TITLE
Allow passing a map[string]func() to AddDynamicField() via exporter options

### ISSUE THREAD

**Issue by lizthegrey** [honeycombio/opentelemetry-exporter-go#52]
We should plumb through as an `Option` the ability to set a string key and a func() value on every span. This is already supported in the libhoney `Client` via `AddDynamicField` but we need some plumbing to make it work.

See https://github.com/open-telemetry/opentelemetry-go/blob/master/exporter/trace/stackdriver/stackdriver.go#L133 for examples of how this is done in other exporters.

request by @seh

**Comment by seh** [comment]
@paulosman, is this work in progress? Could I help here with a patch? If you're already on it, I'll wait, but I have strong interest in putting this to use soon.

**Comment by lizthegrey** [comment]
Feel free to send us a patch if you have time :)

**Comment by paulosman** [comment]
@seh +1 a patch would be great. Thank you!

**Comment by seh** [comment]
As part of this work, I noticed that there are several exported types that don't need to be exported, and at minimum the struct types don't need their fields to be exported. Was that a conscious decision to export them? If not, we can reduce the exported surface area of this "honeycomb" package considerably.

**Comment by seh** [comment]
Please see #54. It goes beyond this narrow request.
