### ISSUE TITLE
core.SpanContext has moved to trace.SpanContext

### ISSUE THREAD

**Issue by Aneurysm9** [honeycombio/opentelemetry-exporter-go#77]
When https://github.com/open-telemetry/opentelemetry-go/pull/692 is released [the translator](https://github.com/honeycombio/opentelemetry-exporter-go/blob/master/honeycomb/translator.go#L45) will need to be updated to reflect the new location of the `SpanContext` type.

**Comment by lizthegrey** [comment]
Yup. That's a breaking enough change I think we should do v0.5.0 on both otel-go and -exporter
